### ISSUE TITLE
Include Document Creation example in ReadMe

### ISSUE THREAD

**Issue by tseven** [tmarois/Filebase#18]
For a new user it is not obvious how to create a document.

The documentation should include these steps:
```php
  $item = new \Filebase\Document($db);
  $item->setId(1);
  $item->name = 'Tom';
  $item->age = 42;
  $item->save();
```

**Comment by timothymarois** [comment]
@tseven Thanks! Always looking for ways to make it easier to understand. That is an interesting way you did that, usually, you can do the `Database` and use `get` method would automatically instantiate `Document`, but I guess you could also call it directly.

**Comment by tseven** [comment]
Ah. I did notice the `get` method being used that way in the ReadMe, but it didn't seem intuitive to try and get a document before it was created; especially in instances when you know the document doesn't exist yet. Also it seems more efficient to directly create the document instead of asking the DB to search for it first.

Thanks

**Comment by timothymarois** [comment]
@tseven You make a good point. Originally was about `get` and if it doesn't exist, you can save it, it would either update or create a new doc. But that I guess isn't as intuitive. I'll address this in a future update. I do plan to have version 2 with a better `Collection` system for arrays as well. The current version was the first iteration I used for many projects, but I think it has grown into something bigger now.
