### ISSUE TITLE
Multiple AND conditions not working as expected

### ISSUE THREAD

**Issue by ONeill1** [tmarois/Filebase#19]
Data structure: 
I've got 10 dummy database entries, one with attr1=123456 and rest with attr1=999999. All entries have attr2='default'.

Code:
$store = new \Filebase\Database([
	'dir' 	=> './store',	
]);
$query = $store->query();
$query->where('attr1','==','123456');
$query->where('attr2','==','default');
$results = $query->results(false);
echo count($results);

I expecting only one result but i get 10. Only the last where/and condition seems to work.

After some digging through the code I've found the potential error:
file QueryLogic.php Line: 144
$documents = array_values(array_filter(**$org_docs**, function ($document) use ($field, $operator, $value) {
If I replace the bold marked part with **$documents** then multiple AND conditions work as expected.

Maybe this isn't even an error and meant by design... :)

**Comment by timothymarois** [comment]
@ONeill1 Thanks for bringing this up. I will take a look at this today and release a patch if I find a fix.

**Comment by timothymarois** [comment]
@ONeill1 I have added the fix you mentioned. That has seemed to resolve the multiple `AND` queries. Let me know if you see any other issues. I haven't done too much testing in the complex querying and could use some help building that section up if it becomes a popular use case.
