### ISSUE TITLE
Duplicated results using orderBy and limit with cache enabled

### ISSUE THREAD

**Issue by AdriaandeJongh** [tmarois/Filebase#52]
Hey there!

With cache enabled, the following query will return the right results the first time it's called, but will show duplicate results from then on.

`$db->query()->orderBy('__created_at', 'DESC')->limit(6)->resultDocuments();`

It appears that the parameter in 'orderBy' can be anything for this bug to appear.

(Sorry for editing this issue 100 times as I kept finding problems / solutions and quickly debunk them after that ;)

**Comment by timothymarois** [comment]
@AdriaandeJongh  Hi, can you share example data of what you're seeing in the results or even a `print_r` of the output. I've tested this using `resultDocuments()` and `results()` but was unable to reproduce the issue of duplicated results. Are you saying you're seeing double results in the cached results?

**Comment by AdriaandeJongh** [comment]
(Sorry again for editing this issue a number of times as I'm discovering what is actually the issue.)

It appears the issue is with `limit(6)`. The following files are versions the cache file resulting from the query in the original post (renamed from .json to .txt so github would take them). So file 1.txt appeared after running the query once, file 2.txt after running it twice, and so on.

[1.txt](https://github.com/filebase/Filebase/files/2898920/1.txt)
[2.txt](https://github.com/filebase/Filebase/files/2898921/2.txt)
[3.txt](https://github.com/filebase/Filebase/files/2898922/3.txt)
[4.txt](https://github.com/filebase/Filebase/files/2898923/4.txt)
[5.txt](https://github.com/filebase/Filebase/files/2898927/5.txt)
[6.txt](https://github.com/filebase/Filebase/files/2898928/6.txt)
[7.txt](https://github.com/filebase/Filebase/files/2898929/7.txt)
[8.txt](https://github.com/filebase/Filebase/files/2898930/8.txt)

**Comment by mikestreety** [comment]
I can confirm I also experience this issue. When I have the cached enabled, every time I press refresh when using the limit I get duplication.

**Comment by gmartino27** [comment]
Have sombody a solution or workaround for this?
I have the same problem, removing the `limit` from the query seems to help but i need a limit..
Else i have to deactivate the cache..
