### ISSUE TITLE
where('IN') returns 1 document

### ISSUE THREAD

**Issue by MarcelHekkert** [tmarois/Filebase#6]
I have created 3 documents all with unique id's of which two contain tag=>php. 

`
$users = $db->query()->where('tags','IN','php')->results();
`

using where('IN') it only returns 1 document. The total count returns 3 (documents) as it should.

**Comment by timothymarois** [comment]
Thanks for pointing that out. I will take a look at that later today.

**Comment by timothymarois** [comment]
Are you using the latest release? 

Here's what I found here, so far the tests have come back as positive. Send me some example data that I can try, here's what I've tested.

**Doc 1:**

```
'Google'=>[ 'tags' => [ 'search','display' ]],
```


**Doc 2:**
```
'Microsoft'=>[ 'tags' => [ 'windows','xbox','search' ] ]
```

`$test4 = $db->query()->where('tags','IN','search')->results();`

Returns 2 documents.

**Comment by timothymarois** [comment]
@MarcelHekkert Send me some sample data so I can run the tests, would love to see what you're working with. So far it should handle what you've given it. Most of what you've pointed out Filebase should be able to handle. And I'm open to new modifications to make things easier, though the API methods should be very intuitive compared to most flat file systems. If there is a missing feature, just let me know and I'll add it to the tasks. 

It should be able to run whatever you like even more complex querying. 

`$db->query()->where('score','>',50)->orderBy('name','ASC')->limit(20)->results();`
