### ISSUE TITLE
Adding New Records

### ISSUE THREAD

**Issue by itsnotyoutoday** [tmarois/Filebase#63]
I like the idea and I was going to use in a prototype project.  However, no matter what i do I can't seem to add a new record.  It just overwrites the database everytime..

For example:
```
$record = new \Filebase\Document($database);
$record->title = "YAY";
$record->set([ 'public_key' => $master->toExtendedPublicKey(), 'private_key' => $master->toExtendedPrivateKey(), 'extended_key' => $master->toExtendedKey()]);
$record->save();

$record = new \Filebase\Document($database);
$record->title = "BLAH";
$record->set([ 'public_key' => $master->toExtendedPublicKey(), 'private_key' => $master->toExtendedPrivateKey(), 'extended_key' => $master->toExtendedKey()]);
$record->save();
```
I would expect that to add two records.. But no, the only one that persists is just BLAH....  Am I missing something?

**Comment by sumpygump** [comment]
I believe what is happening is it your record doesn't end up having an actual id.

Try using this approach instead. 
```
$record = $database->get('YAY');
```

Calling `$database->get()` will fetch the record with that given id or else it will create a new document with that id.
