### ISSUE TITLE
How do I include this script?

### ISSUE THREAD

**Issue by achleitner** [tmarois/Filebase#64]
Hello, sorry for my ignorance, but how would I include this manually in my php file?
Thanks

**Comment by sumpygump** [comment]
Hello achleitner,

To include this in your php script, you should use [composer](https://getcomposer.org/doc/00-intro.md). You can read about composer at the website getcomposer.org.

Once you issue the command using composer in the directory of your PHP project, like `composer require tmarois/filebase`, then composer will create a `vendor` directory. After that, you can use it in your PHP script by including `vendor/autoload.php`, then you have access to any packages you have installed with composer, including Filebase.

```
require_once 'vendor/autoload.php';

$database = new \Filebase\Database([
    'dir' => 'path/to/database/dir'
]);
```

I hope that helps.

**Comment by achleitner** [comment]
Hey, many thanks. I just installed composer following this on Ubuntu : https://linuxize.com/post/how-to-install-and-use-composer-on-ubuntu-18-04/

Seems like things are working now!
You learn something new every day!

**Comment by achleitner** [comment]
Would this be a way for a simple query? 

require_once 'vendor/autoload.php';

// setting the access and configration to your database
$database = new \Filebase\Database([
    'dir' => 'database',
	'cache'          => false
]);

// in this example, you would search an exact user name
// it would technically be stored as user_name.json in the directories
// if user_name.json doesn't exists get will return new empty Document
$results = $database->findAll();


foreach ($results as $user) {
	
		 echo $user->createdAt();
		 
     $user->first_name = 'asfasfasfasfasf';
$results->save();
}

Or should the "save" outside the foreach?

**Comment by timothymarois** [comment]
Hey @achleitner 

```php
require_once 'vendor/autoload.php';

$database = new \Filebase\Database([
   'dir' => 'database',
   'cache' => false
]);

$results = $database->findAll();

foreach ($results as $user) {

     echo $user->createdAt();
     $user->first_name = 'asfasfasfasfasf';
     
     $user->save();
}
```

change `$results->save();` to `$user->save();` 

You save on an individual collection level since `$results` is an array of objects.

**Comment by achleitner** [comment]
Thaks a ton. Really excited trying to implement this on my website for some basic inventory control.

**Comment by achleitner** [comment]
Hello, do I understand this correctly that for each new let's call it record a new file should be created? So let's say I have 10 products I will have 10 json files 1 for each?

Or how would I go about creating a new record in the file?

**Comment by timothymarois** [comment]
Hey @achleitner 

Yes, we'd have 10 files for each item, it does depend on how you want to store your data. but you can follow by the examples located in the readme, 

[Get Items](https://github.com/tmarois/Filebase#3-get-and-methods)

[Create and Update](https://github.com/tmarois/Filebase#4-create--update--delete)

Let me know if that helps.
