### ISSUE TITLE
Is this project still maintained and supported?

### ISSUE THREAD

**Issue by camillo777** [tmarois/Filebase#65]
Hello,
I am going to start a new project (simple private blog/headless cms) and was looking for a file based, no dependency PHP document store.
It seems quite impossible to find one for PHP and that is still maintained and supported.
Filebase seems very cool indeed.
I already have a MySQL installed, but I don't want to structure data in SQL tables and I can't install another DB or other extensions.

So my question is, is this project still supported and working?
Does it provide some decent speed and can be used in a production environment?

PS. I could also save/load JSON objects, but I would like also to search, filter and sort.

Thank you
Camillo

**Comment by timothymarois** [comment]
Hi @camillo777 

yes, the project can be used in Production mode, I use it on my of my projects. It is a JSON file storage, with filters and sorting. You can view all its functionality in the readme. 

We support the development of this package and if there are any issues that arise, we will address them. If there are any severe issues, they will be patched as quickly as possible. Feel free to send in a request or ask for support at any time. 

I wish you the best on your new project!
