### ISSUE TITLE
You didnt tell us how to create a table

### ISSUE THREAD

**Issue by mitmelon** [tmarois/Filebase#71]
How to create a table

**Comment by sumpygump** [comment]
There are no tables with this type of data storage. Each database is just a collection of records each having a fluid schema. Each record can be accessed by its key. Take a look at the usage example in the README to get an idea of how to create a new record (or fetch an existing one).

Does that help?

**Comment by mitmelon** [comment]
> There are no tables with this type of data storage. Each database is just a collection of records each having a fluid schema. Each record can be accessed by its key. Take a look at the usage example in the README to get an idea of how to create a new record (or fetch an existing one).
> 
> Does that help?

Ok thanks it helps...

**Comment by timothymarois** [comment]
If you have any more questions feel free to ask, hope the readme covers most of your needs, if not just let me know and we can always append more documentation. Going to close this for now. Thanks, @sumpygump for the prompt reply.
